# Docker-compose.pinpoint.yml
services:
  collector:
    image: pinpointdocker/pinpoint-collector:3.0.1
    platform: linux/amd64           # <─ 추가
    container_name: pinpoint-collector

  web:
    image: pinpointdocker/pinpoint-web:3.0.1
    platform: linux/amd64           # <─ 추가
    container_name: pinpoint-web
    depends_on: [collector]
    environment:
      COLLECTOR_IP: collector
    ports:
      - "8079:8080" # 인스턴스 포트 

  # app:
  #   image: qrworld-app        # 빌드된 Spring Boot+Agent
  #   environment:
  #     COLLECTOR_IP: collector
  #     PINPOINT_AGENT_ID: qrworld-${HOSTNAME}
  #   ports: ["8080:8080"]
  #   depends_on: [collector]