version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local-docker
      JAVA_OPTS: "-Xms256m -Xmx512m"  # JVM 힙 메모리 제한
    deploy:
      resources:
        limits:
          cpus: '2'    # CPU 2코어로 제한
          memory: 1G   # 전체 메모리 1GB로 제한
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --web.enable-remote-write-receiver
      --enable-feature=native-histograms
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    env_file:
      - .env.local-docker
    environment:
      - DATA_SOURCE_NAME=${DATA_SOURCE_NAME}
    ports:
      - "9187:9187"   # 내부 포트는 9187 그대로, 호스트 포트만 다르게 매핑
    networks:
      - monitoring

  k6:
    image: grafana/k6:latest
    container_name: k6
    command: >
      run -o experimental-prometheus-rw /scripts/test.js
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
    volumes:
      - ./k6-scripts:/scripts
    networks:
      - monitoring
    depends_on:
      - app
      - prometheus
      - grafana
      - postgres_exporter

volumes:
  grafana_data:

networks:
  monitoring: