version: "3.8"

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "2" # CPU 2코어로 제한
          memory: 1G # 전체 메모리 1GB로 제한
        reservations:
          cpus: "0.5"
          memory: 512M
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --web.enable-remote-write-receiver
      --enable-feature=native-histograms
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    env_file:
      - .env
    ports:
      - "9187:9187" # 내부 포트는 9187 그대로, 호스트 포트만 다르게 매핑
    networks:
      - monitoring
  
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: "2" # CPU 2코어로 제한
          memory: 1G # 전체 메모리 1GB로 제한
        reservations:
          cpus: "0.5"
          memory: 512M

volumes:
  grafana_data:
  postgres_data:

networks:
  monitoring:
