version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --web.enable-remote-write-receiver
      --enable-feature=native-histograms
    networks:
      - monitor-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M


volumes:
  grafana_data:

networks:
  monitor-network:
    driver: bridge
