events { }
http {
  upstream backend { server app:8080; } # 여기서 app은 docker-compose.app.yml에서 설정한 컨테이너 이름입니다.
  server {
    listen 80;
    location / {
      proxy_pass http://backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  } 
}