global:
  scrape_interval: 15s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "postgres-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["postgres_exporter.monitoring.local:9187"]

  - job_name: "app"
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app.monitoring.local:8080"]

## 배포용

  # - job_name: "postgres-exporter"
  #   metrics_path: "/metrics"
  #   static_configs:
  #     - targets: ["13.209.176.200:9187"]

  # - job_name: "app"
  #   scrape_interval: 5s
  #   metrics_path: "/actuator/prometheus"
  #   static_configs:
  #     - targets: ["13.125.131.43:80"]
