global:
  scrape_interval: 15s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "postgres-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  # Spring Boot 애플리케이션을 수집하는 새로운 job
  - job_name: "app"
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app:8080"]
